"""
Model Evaluation Module

This file is responsible for computing and displaying various evaluation metrics for models.

=== Included Metrics ===

1. Accuracy: How many predictions were correct overall
   Formula: Correct predictions / Total samples
   Example: 13500 correct out of 14000 test samples → Accuracy = 96.43%

2. Precision (macro average): Among samples predicted as a class, the proportion that truly belong to that class
   Formula: TP / (TP + FP), then averaged across 10 classes
   Example: Predicted 1000 images as "7", 950 of which are truly "7" → Precision(7) = 95%

3. Recall (macro average): Among samples truly belonging to a class, the proportion correctly identified
   Formula: TP / (TP + FN), then averaged across 10 classes
   Example: 1000 "7" images in test set, model correctly identified 950 → Recall(7) = 95%

4. F1-Score (macro average): Harmonic mean of Precision and Recall
   Formula: 2 × Precision × Recall / (Precision + Recall)
   Usage: Comprehensive measure of precision and recall, suitable for imbalanced class scenarios

5. Confusion Matrix: 10×10 matrix
   Rows = true labels, Columns = predicted labels
   Diagonal = number of correct predictions, higher is better
   Off-diagonal = number of misclassifications, shows which digits are easily confused

6. Classification Report: Per-digit Precision/Recall/F1

=== Three Functions ===

- evaluate_model(): Compute all metrics for a single model
- compare_models(): Generate a comparison table for multiple models
- print_evaluation(): Print detailed results for a single model
"""

import numpy as np
from sklearn.metrics import (
    accuracy_score,          # Accuracy
    precision_score,         # Precision
    recall_score,            # Recall
    f1_score,                # F1 Score
    confusion_matrix,        # Confusion Matrix
    classification_report,   # Full Classification Report
)


def evaluate_model(y_true: np.ndarray, y_pred: np.ndarray, model_name: str = "Model") -> dict:
    """
    Compute all evaluation metrics for a single model

    Args:
        y_true: True labels, shape=(N,), values 0-9
        y_pred: Predicted labels from the model, shape=(N,), values 0-9
        model_name: Name of the model (for display, e.g. "CNN" or "KNN (k=5)")

    Returns:
        dict with the following keys:
            - model_name: Name of the model
            - accuracy: Overall accuracy (float between 0 and 1)
            - precision_macro: Macro-averaged precision
            - recall_macro: Macro-averaged recall
            - f1_macro: Macro-averaged F1
            - precision_per_class: Per-class precision, shape=(10,)
            - recall_per_class: Per-class recall, shape=(10,)
            - f1_per_class: Per-class F1, shape=(10,)
            - confusion_matrix: 10x10 confusion matrix
            - report: Full classification report generated by sklearn (string)

    About "macro" averaging:
        macro = compute metrics for each class, then take the average
        Each class has equal weight, so it is not dominated by large classes
    """
    results = {
        "model_name": model_name,

        # ---- Macro-averaged metrics ----
        "accuracy": accuracy_score(y_true, y_pred),  # Overall accuracy
        # average="macro": simple average across 10 classes
        # zero_division=0: return 0 instead of raising error if a class has no predicted samples
        "precision_macro": precision_score(y_true, y_pred, average="macro", zero_division=0),
        "recall_macro": recall_score(y_true, y_pred, average="macro", zero_division=0),
        "f1_macro": f1_score(y_true, y_pred, average="macro", zero_division=0),

        # ---- Per-class metrics ----
        # average=None: returns individual values for each class, shape=(10,)
        "precision_per_class": precision_score(y_true, y_pred, average=None, zero_division=0),
        "recall_per_class": recall_score(y_true, y_pred, average=None, zero_division=0),
        "f1_per_class": f1_score(y_true, y_pred, average=None, zero_division=0),

        # ---- Confusion matrix ----
        # confusion_matrix(y_true, y_pred) returns a 10x10 matrix
        # cm[i][j] = number of samples with true label i predicted as j
        # Diagonal cm[i][i] = number of correct predictions
        "confusion_matrix": confusion_matrix(y_true, y_pred),

        # ---- Full classification report ----
        # Includes per-class precision / recall / f1 / support
        # digits=4: keep 4 decimal places
        "report": classification_report(y_true, y_pred, digits=4, zero_division=0),
    }
    return results


def compare_models(all_results: list[dict]) -> str:
    """
    Generate a comparison table for multiple models (text format)

    Places Accuracy / Precision / Recall / F1 for multiple models in one table for easy comparison.

    Args:
        all_results: List where each element is the return value of evaluate_model()

    Returns:
        str: Formatted table string that can be printed directly

    """
    # Table header
    header = f"{'Model':<25} {'Accuracy':>10} {'Precision':>10} {'Recall':>10} {'F1-Score':>10}"
    separator = "-" * len(header)

    lines = [separator, header, separator]
    for r in all_results:
        # One row per model, left-align model name, right-align numbers, 4 decimal places
        lines.append(
            f"{r['model_name']:<25} "
            f"{r['accuracy']:>10.4f} "
            f"{r['precision_macro']:>10.4f} "
            f"{r['recall_macro']:>10.4f} "
            f"{r['f1_macro']:>10.4f}"
        )
    lines.append(separator)
    return "\n".join(lines)


def print_evaluation(results: dict):
    """
    Print complete evaluation results for a single model to terminal

    Prints:
        - Model name
        - Accuracy / Precision / Recall / F1 (macro average)
        - Per-digit 0-9 detailed metrics (sklearn's classification_report)

    Args:
        results: Return value from evaluate_model()
    """
    print(f"\n{'='*50}")
    print(f"  Model: {results['model_name']}")
    print(f"{'='*50}")
    print(f"  Accuracy:  {results['accuracy']:.4f}")
    print(f"  Precision: {results['precision_macro']:.4f} (macro avg)")
    print(f"  Recall:    {results['recall_macro']:.4f} (macro avg)")
    print(f"  F1-Score:  {results['f1_macro']:.4f} (macro avg)")
    print(f"\n  Per-class details:")
    print(results["report"])
